### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by CHJ85** [borderOS/iceStore#1]
Please add the fullscreen flag "-start-fullscreen" to some of these apps (that's the chromium browsers command). Especially the streaming services such as Netflix. You should also add this feature to the Ice app.
And in isolated browser mode, they give you this message asking if you wish to make it your default browser and send feedback and what not. Please fix this.
In the chromium browsers, you can fix it by setting up the Local State file. Not sure how to do it in Firefox.
Btw, speaking of streaming services. Please add some more of them such as FilmRise, XUMO, Pluto TV (https://pluto.tv/live-tv/), VRV.co, Funimation and Smithsonian Plus (https://watch.smithsonianchannel.com/), MagillanTV and CuriosityStream.

**Comment by PizzaLovingNerd** [comment]
These are issues with ICE, not the Ice Store. Please file a bug report on https://github.com/peppermintOS/ice

**Comment by CHJ85** [comment]
Yea, you're right. Sorry. My bad. 😀
