### ISSUE TITLE
Suggestion for the price label

### ISSUE THREAD

**Issue by tiotrom** [borderOS/iceStore#2]
We all know that pretty much no webapp is "free". Gmail collects your data and inject ads, thus you have to give them your data and attention in return for their service. Same is true for so many. It is no difference between a webapp that asks you for money in order to access it, an one that asks for your data. Thus, these webapps are money free, but not trade free. You trade your data, attention, clicks, whatever.

Thus, I suggest labeling them as "trade-free" or "not trade-free". Like we do for our TROMjaro OS https://www.tromjaro.com/ and https://www.tromjaro.com/apps. Should be more straight forward. 

So, if a WebApp wants something from you in return for the service, it is not trade-free since you have to trade for it. Like if it collects data, or posts ads, or asks you to login, or has premium features for those who pay, and so forth. More about the idea at https://www.trade-free.org/.

Take our tromland.org that offers trade-free webapps. They are what you see: a searxh engine, a file upload/share service, a note taking app. Nothing shady about that. Trade-free. You have to give nothing in return for these services.

I wanted to point that out. To suggest.

**Comment by hpott** [comment]
That is a good idea, but it would be tedious to re-label every single entry in the repository. If you want to follow through with this, I suggest you raise this as an issue in [ririOS/ice-store-repo](https://github.com/risiOS/ice-store-repo) rather than here.
